{% set name = "VeChat" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/HaploKit/vechat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 094e6186f48e08cd2e2896427b8a0dd263bb72330527506df90791d7bf8e7f0d

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - zlib
    - python
    - minimap2
    - yacrd 
    - fpa 0.5

test:
  commands:
    - vechat -h

about:
  home: https://github.com/HaploKit/vechat
  license: GPL-3.0
  license_file: LICENSE
  summary: Correcting errors in noisy long reads using variation graphs
